### ISSUE TITLE
04simbp behavior

### ISSUE THREAD

**Issue by nd** [aarzilli/delve_client_testing#1]
Hi Alessandro!

It's not really an issue, but a question regarding the 04simbp test. If I understand the description correctly with 100 goroutines delve should stop at the breakpoint 100 times, but it doesn't happen: some stops are missed. Is it a bug?

**Comment by aarzilli** [comment]
> delve should stop at the breakpoint 100 times

precisely because sometimes the breakpint is hit multiple times simultaneously, delve will *not* stop 100 times (unless you have a single processor machine or are extremely lucky). The breakpoint will be *hit* a total of 100 times, however. If that doesn't happen it's a bug (but we have a test to check exactly this, so I'm skeptical that it's happening).

**Comment by nd** [comment]
Thank you, now it's clear! The `eventually multiple breakpoints will be hit simultaneously, they should all be notified to the user` in the description means appropriate hit count.

**Comment by aarzilli** [comment]
It means that at some point the breakpoint will be hit simultaneously by two or more goroutines and when that happens the delve client should notify the user that this has happened.
